### ISSUE TITLE
这个程序有问题

### ISSUE THREAD

**Issue by ZhangBeiQing** [hdw09/filtfilt#2]
c++版本我用了一下，设置了5阶36输入，然后输出和MATLAB根本就不同，我还以为是我哪里弄错了，用不同的阶数又试了几遍，还是错的，怎么能这么坑。你发出来不应该检测一下程序的正确性吗。

**Comment by ywchen1994** [comment]
我使用了c++版本9階900輸入結果與Matlab一致，樓上請確認一下，紅色點是板主程式的結果，藍色則是matlab結果
![untitled](https://user-images.githubusercontent.com/20179264/29073500-6c45047a-7c7e-11e7-8e1a-985b9b6644c0.jpg)

**Comment by panoshu** [comment]
感谢 @ywchen1994 的实例，代码都是经过我们测试的，并且已经在特定的场景里稳定使用了，请先确认使用方法是否正确，也可以贴出来大家一起分析下 @ZhangBeiQing
