### ISSUE TITLE
Bug in filter method

### ISSUE THREAD

**Issue by masa2146** [hdw09/filtfilt#4]
Hello, first of all thank you for this java code. However, ı found a bug filter method in Filtfilt class. the part of the bug code is 
```        
changeArray(A, A.get(0));
changeArray(B, A.get(0));
```
when A.get(0) was 1 value then B values does not change.
So ı change it.
New code is

```
double a0 = A.get(0);
changeArray(A, a0);
changeArray(B, a0);

```

**Comment by hdw09** [comment]
多谢反馈，已经修改了
